name: Fetch Stargazers Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC everyday
  workflow_dispatch:      # Allow manual trigger

jobs:
  fetch-stargazers:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run stargazers fetch script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: node scripts/fetch-stargazers.js
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update stargazers data" && git push)